# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "bio-svgenes"
  s.version = "0.3.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Dan MacLean"]
  s.date = "2013-06-06"
  s.description = "This bio-gem facilitates the creation of pretty, publication quality SVG images from feature data."
  s.email = "maclean.daniel@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "bio-svgenes.gemspec",
    "doc/Bio.html",
    "doc/Bio/Graphics.html",
    "doc/Bio/Graphics/Glyph.html",
    "doc/Bio/Graphics/MiniFeature.html",
    "doc/Bio/Graphics/Page.html",
    "doc/Bio/Graphics/Primitive.html",
    "doc/Bio/Graphics/SVGEE.html",
    "doc/Bio/Graphics/Track.html",
    "doc/LICENSE_txt.html",
    "doc/classes/Bio.html",
    "doc/classes/Bio/Graphics.html",
    "doc/classes/Bio/Graphics/Glyph.html",
    "doc/classes/Bio/Graphics/Glyph.src/M000001.html",
    "doc/classes/Bio/Graphics/Glyph.src/M000002.html",
    "doc/classes/Bio/Graphics/Glyph.src/M000003.html",
    "doc/classes/Bio/Graphics/Glyph.src/M000004.html",
    "doc/classes/Bio/Graphics/Glyph.src/M000005.html",
    "doc/classes/Bio/Graphics/Glyph.src/M000006.html",
    "doc/classes/Bio/Graphics/Glyph.src/M000007.html",
    "doc/classes/Bio/Graphics/Glyph.src/M000008.html",
    "doc/classes/Bio/Graphics/Glyph.src/M000009.html",
    "doc/classes/Bio/Graphics/Glyph.src/M000010.html",
    "doc/classes/Bio/Graphics/Glyph.src/M000011.html",
    "doc/classes/Bio/Graphics/Glyph.src/M000012.html",
    "doc/classes/Bio/Graphics/Glyph.src/M000013.html",
    "doc/classes/Bio/Graphics/Glyph.src/M000014.html",
    "doc/classes/Bio/Graphics/Glyph.src/M000015.html",
    "doc/classes/Bio/Graphics/Glyph.src/M000016.html",
    "doc/classes/Bio/Graphics/Glyph.src/M000017.html",
    "doc/classes/Bio/Graphics/Glyph.src/M000018.html",
    "doc/classes/Bio/Graphics/Glyph.src/M000019.html",
    "doc/classes/Bio/Graphics/Glyph.src/M000020.html",
    "doc/classes/Bio/Graphics/Glyph.src/M000021.html",
    "doc/classes/Bio/Graphics/Glyph.src/M000022.html",
    "doc/classes/Bio/Graphics/Glyph.src/M000023.html",
    "doc/classes/Bio/Graphics/Glyph.src/M000024.html",
    "doc/classes/Bio/Graphics/MiniFeature.html",
    "doc/classes/Bio/Graphics/MiniFeature.src/M000001.html",
    "doc/classes/Bio/Graphics/MiniFeature.src/M000003.html",
    "doc/classes/Bio/Graphics/MiniFeature.src/M000024.html",
    "doc/classes/Bio/Graphics/Page.html",
    "doc/classes/Bio/Graphics/Page.src/M000010.html",
    "doc/classes/Bio/Graphics/Page.src/M000011.html",
    "doc/classes/Bio/Graphics/Page.src/M000012.html",
    "doc/classes/Bio/Graphics/Page.src/M000013.html",
    "doc/classes/Bio/Graphics/Page.src/M000014.html",
    "doc/classes/Bio/Graphics/Page.src/M000015.html",
    "doc/classes/Bio/Graphics/Page.src/M000016.html",
    "doc/classes/Bio/Graphics/Page.src/M000017.html",
    "doc/classes/Bio/Graphics/Page.src/M000018.html",
    "doc/classes/Bio/Graphics/Page.src/M000019.html",
    "doc/classes/Bio/Graphics/Page.src/M000020.html",
    "doc/classes/Bio/Graphics/Page.src/M000021.html",
    "doc/classes/Bio/Graphics/Page.src/M000022.html",
    "doc/classes/Bio/Graphics/Page.src/M000023.html",
    "doc/classes/Bio/Graphics/Page.src/M000024.html",
    "doc/classes/Bio/Graphics/Page.src/M000025.html",
    "doc/classes/Bio/Graphics/Page.src/M000026.html",
    "doc/classes/Bio/Graphics/Page.src/M000027.html",
    "doc/classes/Bio/Graphics/Page.src/M000028.html",
    "doc/classes/Bio/Graphics/Page.src/M000029.html",
    "doc/classes/Bio/Graphics/Page.src/M000030.html",
    "doc/classes/Bio/Graphics/Page.src/M000031.html",
    "doc/classes/Bio/Graphics/Page.src/M000032.html",
    "doc/classes/Bio/Graphics/Page.src/M000033.html",
    "doc/classes/Bio/Graphics/Page.src/M000034.html",
    "doc/classes/Bio/Graphics/Page.src/M000035.html",
    "doc/classes/Bio/Graphics/Page.src/M000036.html",
    "doc/classes/Bio/Graphics/Page.src/M000037.html",
    "doc/classes/Bio/Graphics/Page.src/M000038.html",
    "doc/classes/Bio/Graphics/Page.src/M000039.html",
    "doc/classes/Bio/Graphics/Page.src/M000040.html",
    "doc/classes/Bio/Graphics/Page.src/M000041.html",
    "doc/classes/Bio/Graphics/Page.src/M000042.html",
    "doc/classes/Bio/Graphics/Page.src/M000043.html",
    "doc/classes/Bio/Graphics/Page.src/M000044.html",
    "doc/classes/Bio/Graphics/Primitive.html",
    "doc/classes/Bio/Graphics/Primitive.src/M000001.html",
    "doc/classes/Bio/Graphics/Primitive.src/M000002.html",
    "doc/classes/Bio/Graphics/Primitive.src/M000008.html",
    "doc/classes/Bio/Graphics/Primitive.src/M000009.html",
    "doc/classes/Bio/Graphics/Primitive.src/M000022.html",
    "doc/classes/Bio/Graphics/Primitive.src/M000023.html",
    "doc/classes/Bio/Graphics/SVGEE.html",
    "doc/classes/Bio/Graphics/SVGEE.src/M000002.html",
    "doc/classes/Bio/Graphics/SVGEE.src/M000003.html",
    "doc/classes/Bio/Graphics/SVGEE.src/M000004.html",
    "doc/classes/Bio/Graphics/SVGEE.src/M000005.html",
    "doc/classes/Bio/Graphics/SVGEE.src/M000006.html",
    "doc/classes/Bio/Graphics/SVGEE.src/M000007.html",
    "doc/classes/Bio/Graphics/SVGEE.src/M000008.html",
    "doc/classes/Bio/Graphics/SVGEE.src/M000009.html",
    "doc/classes/Bio/Graphics/SVGEE.src/M000016.html",
    "doc/classes/Bio/Graphics/SVGEE.src/M000017.html",
    "doc/classes/Bio/Graphics/SVGEE.src/M000018.html",
    "doc/classes/Bio/Graphics/SVGEE.src/M000019.html",
    "doc/classes/Bio/Graphics/SVGEE.src/M000020.html",
    "doc/classes/Bio/Graphics/SVGEE.src/M000021.html",
    "doc/classes/Bio/Graphics/Track.html",
    "doc/classes/Bio/Graphics/Track.src/M000001.html",
    "doc/classes/Bio/Graphics/Track.src/M000002.html",
    "doc/classes/Bio/Graphics/Track.src/M000003.html",
    "doc/classes/Bio/Graphics/Track.src/M000004.html",
    "doc/classes/Bio/Graphics/Track.src/M000010.html",
    "doc/classes/Bio/Graphics/Track.src/M000011.html",
    "doc/classes/Bio/Graphics/Track.src/M000012.html",
    "doc/classes/Bio/Graphics/Track.src/M000013.html",
    "doc/created.rid",
    "doc/files/lib/bio-svgenes_rb.html",
    "doc/files/lib/bio/graphics/glyph_rb.html",
    "doc/files/lib/bio/graphics/mini_feature_rb.html",
    "doc/files/lib/bio/graphics/page_rb.html",
    "doc/files/lib/bio/graphics/primitive_rb.html",
    "doc/files/lib/bio/graphics/svgee_rb.html",
    "doc/files/lib/bio/graphics/track_rb.html",
    "doc/fr_class_index.html",
    "doc/fr_file_index.html",
    "doc/fr_method_index.html",
    "doc/images/add.png",
    "doc/images/arrow_up.png",
    "doc/images/brick.png",
    "doc/images/brick_link.png",
    "doc/images/bug.png",
    "doc/images/bullet_black.png",
    "doc/images/bullet_toggle_minus.png",
    "doc/images/bullet_toggle_plus.png",
    "doc/images/date.png",
    "doc/images/delete.png",
    "doc/images/find.png",
    "doc/images/loadingAnimation.gif",
    "doc/images/macFFBgHack.png",
    "doc/images/package.png",
    "doc/images/page_green.png",
    "doc/images/page_white_text.png",
    "doc/images/page_white_width.png",
    "doc/images/plugin.png",
    "doc/images/ruby.png",
    "doc/images/tag_blue.png",
    "doc/images/tag_green.png",
    "doc/images/transparent.png",
    "doc/images/wrench.png",
    "doc/images/wrench_orange.png",
    "doc/images/zoom.png",
    "doc/index.html",
    "doc/js/darkfish.js",
    "doc/js/jquery.js",
    "doc/js/navigation.js",
    "doc/js/search.js",
    "doc/js/search_index.js",
    "doc/js/searcher.js",
    "doc/manual/bootstrap/css/bootstrap-responsive.css",
    "doc/manual/bootstrap/css/bootstrap-responsive.min.css",
    "doc/manual/bootstrap/css/bootstrap.css",
    "doc/manual/bootstrap/css/bootstrap.min.css",
    "doc/manual/bootstrap/img/glyphicons-halflings-white.png",
    "doc/manual/bootstrap/img/glyphicons-halflings.png",
    "doc/manual/bootstrap/js/bootstrap.js",
    "doc/manual/bootstrap/js/bootstrap.min.js",
    "doc/manual/img/circle.png",
    "doc/manual/img/directed.png",
    "doc/manual/img/down_triangle.png",
    "doc/manual/img/histogram.png",
    "doc/manual/img/span.png",
    "doc/manual/img/transcript.png",
    "doc/manual/img/up_triangle.png",
    "doc/manual/manual.html",
    "doc/manual/manual.md",
    "doc/rdoc-style.css",
    "doc/rdoc.css",
    "doc/table_of_contents.html",
    "examples/data.txt",
    "examples/draw_from_json.rb",
    "examples/example.rb",
    "examples/example.svg",
    "examples/example2.rb",
    "examples/example_config.json",
    "examples/gene.gff",
    "examples/transcripts.gff",
    "lib/bio-svgenes.rb",
    "lib/bio/graphics/glyph.rb",
    "lib/bio/graphics/mini_feature.rb",
    "lib/bio/graphics/page.rb",
    "lib/bio/graphics/primitive.rb",
    "lib/bio/graphics/svgee.rb",
    "lib/bio/graphics/track.rb",
    "test/helper.rb",
    "test/json_config.json",
    "test/test_glyph.rb",
    "test/test_mini_feature.rb",
    "test/test_page.rb",
    "test/test_primitive.rb",
    "test/test_svgee.rb",
    "test/test_track.rb",
    "test/test_transcripts.gff"
  ]
  s.homepage = "http://github.com/danmaclean/bioruby-svgenes"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.25"
  s.summary = "Create pretty SVG-format images of features, gene models and data tracks"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<bio>, [">= 1.4.2"])
      s.add_development_dependency(%q<json>, [">= 1.7"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<bio>, [">= 1.4.2"])
      s.add_dependency(%q<json>, [">= 1.7"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<bio>, [">= 1.4.2"])
    s.add_dependency(%q<json>, [">= 1.7"])
  end
end

